import type { UserRole } from "@type/roles";

export const roleRoutes: Record<UserRole, string[]> = {
  Solicitante: [
    "/dashboard",
    "/perfil-usuario",
    "/crear-solicitud",
    "/historial",
    "/reembolso",
    "/solicitudes-draft",
    "/comprobar-gastos",
    "/completar-draft/*",
    "/editar-solicitud/*",
    "/comprobar-solicitud/*",
    "/detalles-solicitud/*",
    "/subir-comprobante/*",
    "/resubir-comprobante/*",
  ],
  "Agencia de viajes": [
    "/dashboard",
    "/perfil-usuario",
    "/atenciones",
    "/atender-solicitud/*",
  ],
  "Cuentas por pagar": [
    "/dashboard",
    "/perfil-usuario",
    "/cotizaciones",
    "/comprobaciones",
    "/cotizar-solicitud/*",
    "/comprobar-gastos",
    "/comprobar-gastos/*",
    "/comprobar-solicitud/*",
  ],
  N1: [
    "/dashboard",
    "/perfil-usuario",
    "/solicitudes-autorizador",
    "/crear-solicitud",
    "/historial",
    "/reembolso",
    "/solicitudes-draft",
    "/comprobar-gastos",
    "/completar-draft/*",
    "/editar-solicitud/*",
    "/comprobar-solicitud/*",
    "/autorizaciones",
    "/aprobaciones",
    "/detalles-solicitud/*",
    "/autorizar-solicitud/*",
    "/subir-comprobante/*",
  ],
  N2: [
    "/dashboard",
    "/perfil-usuario",
    "/solicitudes-autorizador",
    "/crear-solicitud",
    "/historial",
    "/reembolso",
    "/solicitudes-draft",
    "/comprobar-gastos",
    "/completar-draft/*",
    "/editar-solicitud/*",
    "/comprobar-solicitud/*",
    "/autorizaciones",
    "/aprobaciones",
    "/detalles-solicitud/*",
    "/autorizar-solicitud/*",
    "/subir-comprobante/*",
  ],
  Administrador: [
    "/dashboard",
    "/perfil-usuario",
    "/crear-usuario",
    "/editar-usuario/*",
    // M2-006 — Administración de políticas de viáticos
    "/admin/expense-policies",
    "/admin/employee-categories",
    "/admin/refund-time-limits",
    // Multi-tenant — Gestión de organizaciones (super-admin Ditta).
    // El backend valida por permiso organization:list_all; aquí permitimos la ruta
    // y dejamos que la UI muestre "sin permiso" si el role no es Admin Ditta.
    "/admin/organizations",
  ],
};

export const allWhitelistedRoutes: string[] = Object.values(roleRoutes).flat();
