import type { UserRole } from "@type/roles";

/** Rutas de administración para el admin de una org cliente (sin gestión cross-tenant). */
const routesAdministracionOrgAdmin: string[] = [
  "/dashboard",
  "/perfil-usuario",
  "/crear-usuario",
  "/editar-usuario/*",
  "/admin/expense-policies",
  "/admin/employee-categories",
  "/admin/refund-time-limits",
  "/admin/onboarding-import",
  "/admin/catalogo-contable",
  "/admin/indicadores-impuesto",
  "/admin/mapeo-gastos",
  "/admin/api-keys",
  "/reportes/gastos-por-centro",
];

/** Super-admin Ditta: mismas rutas de org + listado/creación de organizaciones. */
const routesAdministracionDitta: string[] = [
  ...routesAdministracionOrgAdmin,
  "/admin/organizations",
];

export const roleRoutes: Record<UserRole, string[]> = {
  Solicitante: [
    "/dashboard",
    "/perfil-usuario",
    "/crear-solicitud",
    "/historial",
    "/reembolso",
    "/solicitudes-draft",
    "/comprobar-gastos",
    "/completar-draft/*",
    "/editar-solicitud/*",
    "/comprobar-solicitud/*",
    "/resumen-tramos",
    "/resumen-tramos/*",
    "/detalles-solicitud/*",
    "/subir-comprobante/*",
    "/resubir-comprobante/*",
  ],
  "Agencia de viajes": [
    "/dashboard",
    "/perfil-usuario",
    "/atenciones",
    "/atender-solicitud/*",
  ],
  "Cuentas por pagar": [
    "/dashboard",
    "/perfil-usuario",
    "/todas-las-solicitudes",
    "/cotizaciones",
    "/comprobaciones",
    "/exportar-contable",
    "/reportes/gastos-por-centro",
    "/cotizar-solicitud/*",
    "/comprobar-gastos",
    "/comprobar-gastos/*",
    "/comprobar-solicitud/*",
    "/resumen-tramos",
    "/resumen-tramos/*",
    "/detalles-solicitud/*",
  ],
  N1: [
    "/dashboard",
    "/perfil-usuario",
    "/solicitudes-autorizador",
    "/crear-solicitud",
    "/historial",
    "/reembolso",
    "/solicitudes-draft",
    "/comprobar-gastos",
    "/completar-draft/*",
    "/editar-solicitud/*",
    "/comprobar-solicitud/*",
    "/resumen-tramos",
    "/resumen-tramos/*",
    "/autorizaciones",
    "/aprobaciones",
    "/detalles-solicitud/*",
    "/autorizar-solicitud/*",
    "/subir-comprobante/*",
    "/reportes/gastos-por-centro",
  ],
  N2: [
    "/dashboard",
    "/perfil-usuario",
    "/solicitudes-autorizador",
    "/crear-solicitud",
    "/historial",
    "/reembolso",
    "/solicitudes-draft",
    "/comprobar-gastos",
    "/completar-draft/*",
    "/editar-solicitud/*",
    "/comprobar-solicitud/*",
    "/resumen-tramos",
    "/resumen-tramos/*",
    "/autorizaciones",
    "/aprobaciones",
    "/detalles-solicitud/*",
    "/autorizar-solicitud/*",
    "/subir-comprobante/*",
    "/reportes/gastos-por-centro",
  ],
  Administrador: [...routesAdministracionOrgAdmin, "/admin/workflow-rules"],
  "Admin Ditta": routesAdministracionDitta,
};

export const allWhitelistedRoutes: string[] = Object.values(roleRoutes).flat();
